name: CodeCertain
run-name: Generating a report for your most pushed commit
on:
  push:
    paths:
      - '**.java'
      - '**.py'
      - '**.cpp'
jobs:
  Generate-And-Push-Report:
    runs-on: ubuntu-latest
    steps:
      - name: Formatting Variables
        run: echo "BRANCH=$(echo $GITHUB_REF_NAME | sed 's/\//\%SL/g')" >> $GITHUB_ENV
      - name: Print URL
        run: |
          echo "The string is: https://dcp.codecertain.ai/data_create_predict/commit/$GITHUB_REPOSITORY/$BRANCH/$GITHUB_SHA/GitHub/$GITHUB_TOKEN/true/full"
      - name: Analyze Commit
        id: dcp
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://dcp.codecertain.ai/data_create_predict/commit/$GITHUB_REPOSITORY/$BRANCH/$GITHUB_SHA/GitHub/${{ secrets.GITHUB_TOKEN }}/true/full"
          method: 'GET'
          contentType: 'application/json'
          timeout: 900000
      - name: Generate Report
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://mlp.codecertain.ai/ml_predict/commit/$GITHUB_REPOSITORY/$BRANCH/$GITHUB_REPOSITORY/$BRANCH/GitHub/${{ secrets.GITHUB_TOKEN }}/$GITHUB_SHA/None/None/None/true/full/${{ fromJson(steps.dcp.outputs.response).message }}"
          method: 'GET'
          contentType: 'application/json'
          timeout: 900000
